# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13607bc07847b3d123d103ea0ecf05d811957c5a61f319f07c489ab61fc3324011777af1979ade3016a56b877b5339e53aef5c1d262484ee9855e4ecaace71c7

test:
  secret_key_base: bcc53c82eb973eb559098215271f7339749c24138e693606f676da82451520260dcef567c5a36aa67e5b3243ff9dd540e658800efe7c6231e8046b8df302a8e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
